### ISSUE TITLE
Snap assist does not easily allow you to move a window out of snap in Electron

### ISSUE THREAD

**Issue by bingenito** [morganstanley/desktopJS#116]
Identify change between electron@1.6.6 and 1.6.7 which causes issue
https://github.com/electron/electron/compare/v1.6.6...v1.6.7

To reproduce, install electron@1.6.6.  While getting snap assist you can still easily move a window away from the snap threshold.  Upgrade to electron@1.6.7 or later and the stickiness of the snap requires you to move the window fast and a large amount to leave snap threshold.

**Comment by bingenito** [comment]
Debouncing the move event (at any rate including 0) makes it less sticky which is an improvement but it bounces between snap/unsnap to make dragging on edges very shaky.

**Comment by bingenito** [comment]
Debounce has no negative impact on OpenFin snap assist so this can be a short term solution to at least make the Electron experience a tiny bit better.

**Comment by naknode** [comment]
What is stopping from upgrading Electron to its latest (or another major version)?

**Comment by bingenito** [comment]
I'm on 3 now and it is ok. I made a prior commit that improved this behavior dramatically but I kept the issue open as it still wasn't ideal. The versions in here are more for historical note of what electron release introduced the issue.
