### ISSUE TITLE
Use a Code Formatter

### ISSUE THREAD

**Issue by Brookke** [morganstanley/desktopJS#312]
Prettier.io seems to be the goto.

Will likely require some TSLint changes so #311 should probably be done first.

**Comment by Brookke** [comment]
@bingenito Similar to #311 do you have a preference on prettier formatting? I notice the editor config is 4 spaces indentation but I wonder if 2 spaces would be more suited since prettier has a tendency to indent often

**Comment by Brookke** [comment]
I also think it would be great if the prettier config was its own package that could be used in all Morgan Stanley open sourced project, possibly even internally too. Similar to https://github.com/azz/prettier-config

**Comment by bingenito** [comment]
@Brookke Agreed on prettier.  No real preference on spaces of 2 versus 4.  Let's encapsulate within here first and then look to split to another repository based on some of the other projects within the org.
