### ISSUE TITLE
Saved Layout is not correct

### ISSUE THREAD

**Issue by Sly1024** [morganstanley/desktopJS#482]
For saving the window position/location, the `buildLayout` function uses the `nativeWindow` and its `screenX`, `screenY` properties, but it might not be correct in some containers. 

https://github.com/morganstanley/desktopJS/blob/af08a2aed62c53b98434d11083b81ff5dad88e71/packages/desktopjs/src/Default/default.ts#L391

`buildLayout` should use the underlying container's `getBounds` function to get the correct bounds.

**Comment by bingenito** [comment]
This is the default browser implementation.  Each concrete container overrides buildLayout

https://github.com/morganstanley/desktopJS/blob/main/packages/desktopjs-openfin/src/openfin.ts#L694
https://github.com/morganstanley/desktopJS/blob/main/packages/desktopjs-electron/src/electron.ts#L506

**Comment by Sly1024** [comment]
I'll add this to our container implementation.

**Comment by bingenito** [comment]
Looks like #313 changed buildLayout but we missed matching getBounds
